version: 1.0.{build}
platform: x64
# Do not build on tags (GitHub and BitBucket)
skip_tags: false
deploy: off
environment:
  NPM_TOKEN:
    secure: bgYLhLG0cR2eMCMyJ3DLdCEEbRe6SFhjIMr0zxrgc4QbfbsGKZgtLeo7p/W6M6+8
install:
- ps: >-
    Install-Product node 8.1 x64

    node --version

    npm --version

    yarn --version
cache:
- "%LOCALAPPDATA%\\Yarn"
- node_modules
build_script:
- cmd: >-
    yarn install --frozen-lockfile

deploy_script:
- ps: |
    if ($ENV:APPVEYOR_REPO_TAG)
    {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm pack"
        iex "npm publish"
    }
